### ISSUE TITLE
Tensorflow-tutorials/tutorial-2-image-classifier/train.py error

### ISSUE THREAD

**Issue by airbak** [legolas123/cv-tricks.com#17]
~/git/cv-tricks.com/Tensorflow-tutorials/tutorial-2-image-classifier$ python train.py --train training_data/ --val testing_data/ --num_classes 2
Going to read training images
Now going to read dogs files (Index: 0)
Now going to read cats files (Index: 1)
Complete reading input data. Will Now print a snippet of it
Number of files in Training-set:                800
Number of files in Validation-set:      200
WARNING:tensorflow:From train.py:44: calling argmax (from tensorflow.python.ops.math_ops) with dimension is deprecated and will be removed in a future version.
Instructions for updating:
Use the `axis` argument instead
WARNING:tensorflow:From train.py:160: softmax_cross_entropy_with_logits (from tensorflow.python.ops.nn_ops) is deprecated and will be removed in a future version.
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See @{tf.nn.softmax_cross_entropy_with_logits_v2}.

Training Epoch 1 --- Training Accuracy:  50.0%, Validation Accuracy:  43.8%,  Validation Loss: 0.705
2018-08-17 16:52:14.024307: W tensorflow/core/framework/op_kernel.cc:1275] OP_REQUIRES failed at save_restore_v2_ops.cc:109 : Not found: ; No such file or directory
Traceback (most recent call last):
  File "train.py", line 206, in <module>
    train(num_iteration=3000)
  File "train.py", line 201, in train
    saver.save(session, 'dogs-cats-model')
  File "/home/Wukong2/l00176142/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1637, in save
    raise exc
ValueError: Parent directory of dogs-cats-model doesn't exist, can't save.

**Comment by airbak** [comment]
@@ -193,12 +193,12 @@ def train(num_iteration):
-            saver.save(session, 'dogs-cats-model')
+            saver.save(session, './dogs-cats-model')

Modify the path could fix it .
